runtime: python36 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: ''
  MYSQL_DB: 'CS411_Project'
  MYSQL_HOST: '127.0.0.1'

handlers:

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles